version: '2'

services:
  postgres9:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
volumes:
  data: {}